### ISSUE TITLE
А где у вас Посгрес?

### ISSUE THREAD

**Issue by SergeyMirvoda** [Tsypaev/fake-lucene-backend#5]

**Comment by Tsypaev** [comment]
Spring сам всё подключает, ему достаточно передать всё в конфиге
https://github.com/Tsypaev/fake-lucene-backend/blob/master/src/main/resources/application.properties

**Comment by SergeyMirvoda** [comment]
Код на sql где?

**Comment by Tsypaev** [comment]
https://github.com/Tsypaev/fake-lucene-backend/blob/master/src/main/java/ru/tsypaev/database/backend/dataretrieval/repository/MoviesRepository.java

**Comment by SergeyMirvoda** [comment]
Не вижу поиска по нескольким словам неподряд и по нескольким частям.

Не вижу поиска без учёта регистра.

Зачем union all?



пн, 1 апр. 2019 г., 19:07 Vladimir <notifications@github.com>:

**Comment by Tsypaev** [comment]
@SergeyMirvoda , исправлено
